CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    company VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    salary DECIMAL(15,2) NOT NULL,
    posted_date DATE NOT NULL
);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    applicant_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    resume TEXT NOT NULL,
    application_date DATE NOT NULL,
    FOREIGN KEY (job_id) REFERENCES jobs(id)
);
